const SCHEDULE = {
  0: "Sleep Time",
  1: "Sleep Time",
  2: "Sleep Time",
  3: "Sleep Time",
  4: "Sleep Time",
  5: "Sleep Time",
  6: "Sleep Time",
  7: "Sleep Time",
  8: "Sleep Time",
  9: "Nap Time",
  10: "Play Time",
  11: "Nap Time",
  12: "Play Time",
  13: "Nap Time",
  14: "Play Time",
  15: "Nap Time",
  16: "Nap Time",
  17: "Play Time",
  18: "Play Time",
  19: "Sleep Time",
  20: "Sleep Time",
  21: "Sleep Time",
  22: "Sleep Time",
  23: "Sleep Time",
};
